name: php images publish


on:
  push:
    branches: 
      - master
  

jobs:

  publish:
    if: "!contains(github.event.head_commit.message, 'wip')"
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        version: [8.1, 8.2, 8.3, 8.4]
        target: [fpm, tester, websocket, worker, scheduler, composer]
    
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
      
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}   

    - 
      name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: defstudio/php:${{matrix.version}}-${{matrix.target}}
        target: ${{matrix.target}}
        build-args: 
          PHP_VERSION=${{matrix.version}}
